# Generated by Django 4.1.1 on 2022-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('review', 'Review')], default='review', max_length=255),
        ),
    ]
